# This workflows will create a new demo repository using The Hatchlor for demonstration purposes

name: Build demo

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Project configuration'
        required: true
        type: choice
        options:
          - default.yml
          - lock-file.yml

jobs:
  make-demo:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        path: ./hatchlor-template

    - name: Setup Python environment
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: 'latest'
        environment-file: ./hatchlor-template/.github/test_environment.yml
        init-shell: >-
          bash
          powershell
        cache-environment: true
        post-cleanup: 'all'

    - name: Setup git
      run: |
        git config --global user.email "github.action@example.com"
        git config --global user.name "Github Action"

    - name: Run cookiecutter
      run: cookiecutter --no-input ./hatchlor-template --config-file ./hatchlor-template/configs/${{ github.event.inputs.config }}

    - name: Test some hatch commands
      working-directory: ./hatchlor-demo
      run: |
        hatch run cov
        hatch run lint
        hatch run pre-commit run --all-files

    - name: Remove git repo for next step
      working-directory: ./hatchlor-demo
      run: rm -rf .git

    - name: Push to the-hatchlor-demo-bartosz121
      uses: cpina/github-action-push-to-another-repository@devel
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: "hatchlor-demo/"
        destination-github-username: "bartosz121"
        destination-repository-username: "bartosz121"
        destination-repository-name: "the-hatchlor-demo-bartosz121"
        user-email: "admin@bartoszmagiera.dev"
        commit-message: "Initial commit"
        target-branch: main
